<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElSelect,ElOption } from 'element-plus'
import MediaViewer,{type MediaViewerItem} from '../components/MediaViewer.vue'
import FavoriteHeart from '../components/FavoriteHeart.vue'
import { favoriteAsset } from '../api/apiService'
interface Asset{id:number;location:string;asset_type?:'picture'|'video';tag?:number;created_at?:string;name?:string}
const route=useRoute(),router=useRouter(),project=ref<any>(null),assets=ref<Asset[]>([]),loading=ref(true),loadingMore=ref(false),page=ref(1),total=ref(0),media=ref('all'),category=ref('all'),favorite=ref('all'),date=ref('all'),preview=ref<Asset|null>(null)
const user=()=>{try{return JSON.parse(localStorage.getItem('user')||'null')}catch{return null}}
const url=(location:string)=>/^https?:\/\//.test(location)?location:`/api/api-proxy/output/${location.split(/[/\\]/).pop()}`
const item=computed<MediaViewerItem|null>(()=>preview.value?{id:preview.value.id,src:url(preview.value.location),type:preview.value.asset_type==='video'?'video':'image',title:preview.value.name||preview.value.location.split(/[/\\]/).pop()}:null)
function cachedProject(){try{const value=JSON.parse(sessionStorage.getItem('active-project')||'null');return Number(value?.project?.id)===Number(route.params.id)?value:null}catch{return null}}
async function load(reset=true){if(reset){page.value=1;loading.value=true}else loadingMore.value=true;try{const id=Number(route.params.id),uid=user()?.id;if(reset||!project.value){const detail=await fetch(`/api/api-proxy/projects/${id}?user_id=${uid}`);if(!detail.ok)throw new Error();project.value=(await detail.json()).project}const params=new URLSearchParams({user_id:String(uid),project_id:String(id),page:String(page.value),page_size:'30'});if(media.value!=='all')params.set('asset_type',media.value);if(category.value!=='all')params.set('category_id',category.value);if(favorite.value!=='all')params.set('tag',favorite.value);if(date.value!=='all')params.set('date_range',date.value);const response=await fetch(`/api/api-proxy/user/assets?${params}`);if(!response.ok)throw new Error();const data=await response.json();assets.value=reset?(data.assets||[]):[...assets.value,...(data.assets||[])];total.value=data.total||0}catch{const cached=cachedProject();if(cached){project.value=cached.project;let fallback:Asset[]=cached.assets||[];if(media.value!=='all')fallback=fallback.filter(a=>a.asset_type===media.value);if(category.value!=='all'){const ids=new Set((cached.project.categories||[]).find((c:any)=>String(c.id)===category.value)?.assets||[]);fallback=fallback.filter(a=>ids.has(a.id))}if(favorite.value!=='all')fallback=fallback.filter(a=>(a.tag||0)===Number(favorite.value));if(date.value!=='all'){const cutoff=Date.now()-Number(date.value)*86400000;fallback=fallback.filter(a=>new Date(a.created_at||0).getTime()>=cutoff)}assets.value=fallback;total.value=fallback.length}else{project.value={id:Number(route.params.id),name:'项目不可用',asset_count:0,scope:'personal'};assets.value=[];total.value=0}}finally{loading.value=false;loadingMore.value=false}}
function loadMore(){page.value+=1;load(false)}
async function setFavorite(asset:Asset,tag:0|1|2|3|4){const uid=user()?.id;if(uid)await favoriteAsset(asset.id,uid,tag);asset.tag=tag}
function download(asset:Asset){const a=document.createElement('a');a.href=url(asset.location);a.download=asset.name||asset.location.split(/[/\\]/).pop()||'asset';a.click()}
watch([media,category,favorite,date],()=>load(true));onMounted(()=>load(true))
</script>
<template>
  <main class="detail">
    <header><button @click="router.push('/')">工作台</button><span>/</span><strong>{{project?.name||'加载中'}}</strong><small v-if="project">{{project.asset_count||assets.length}} 项 · {{project.scope==='shared'?`团队共享 ${project.member_count||1} 人`:'我的项目'}}</small></header>
    <section class="filters"><nav><button :class="{active:media==='all'}" @click="media='all'">全部</button><button :class="{active:media==='picture'}" @click="media='picture'">图片</button><button :class="{active:media==='video'}" @click="media='video'">视频</button></nav><div><ElSelect v-model="category"><ElOption label="全部分类" value="all"/><ElOption v-for="c in project?.categories||[]" :key="c.id" :label="c.name" :value="String(c.id)"/></ElSelect><ElSelect v-model="favorite"><ElOption label="全部收藏" value="all"/><ElOption label="未收藏" value="0"/><ElOption label="红色" value="1"/><ElOption label="黄色" value="2"/><ElOption label="绿色" value="3"/><ElOption label="蓝色" value="4"/></ElSelect><ElSelect v-model="date"><ElOption label="全部时间" value="all"/><ElOption label="最近 7 天" value="7"/><ElOption label="最近 30 天" value="30"/></ElSelect></div></section>
    <div v-if="loading" class="state">正在加载素材…</div><div v-else-if="!assets.length" class="state">当前项目暂无素材</div>
    <section v-else class="masonry"><article v-for="asset in assets" :key="asset.id"><img v-if="asset.asset_type!=='video'" :src="url(asset.location)" @click="preview=asset"/><video v-else :src="url(asset.location)" muted preload="metadata" @click="preview=asset"/><div class="asset-actions"><button title="下载" @click.stop="download(asset)">↓</button><FavoriteHeart :tag="asset.tag||0" @change="tag=>setFavorite(asset,tag)"/></div></article></section>
    <button v-if="assets.length<total" class="load-more" :disabled="loadingMore" @click="loadMore">{{loadingMore?'加载中…':'加载更多'}}</button>
    <MediaViewer :visible="Boolean(preview)" :item="item" @close="preview=null"/>
  </main>
</template>
<style scoped>
.detail{min-height:calc(100vh - 22px);padding:36px 40px 80px;color:var(--color-text);background:linear-gradient(180deg,rgba(2,4,8,.66),rgba(2,4,8,.56) 48%,rgba(2,4,8,.72))}header{display:flex;align-items:center;gap:9px;height:28px;color:var(--color-faint);font-size:12px}header button{border:0;background:none;color:var(--color-muted);cursor:pointer}header strong{overflow:hidden;max-width:320px;color:var(--color-text);font-size:15px;font-weight:560;text-overflow:ellipsis;white-space:nowrap}header small{margin-left:3px;color:var(--color-faint)}.filters{margin:24px 0 22px;display:flex;align-items:end;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.07)}.filters nav{display:flex;gap:25px}.filters nav button{padding:0 0 11px;border:0;border-bottom:1px solid transparent;background:none;color:var(--color-muted);cursor:pointer}.filters nav button.active{border-color:var(--color-primary);color:var(--color-text)}.filters>div{display:flex;gap:8px}.filters :deep(.el-select){width:112px}.filters :deep(.el-select__wrapper){border:0!important;background:transparent!important;box-shadow:none!important}.masonry{columns:4 230px;column-gap:14px}.masonry article{position:relative;margin-bottom:14px;break-inside:avoid;overflow:hidden;border-radius:7px}.masonry img,.masonry video{display:block;width:100%;max-height:420px;object-fit:cover;cursor:pointer;filter:brightness(.88)}.asset-actions{position:absolute;top:8px;right:8px;display:flex;align-items:center;gap:5px;opacity:0;transition:opacity .18s}.masonry article:hover .asset-actions{opacity:1}.asset-actions button{width:28px;height:28px;border:1px solid rgba(255,255,255,.16);border-radius:6px;background:rgba(4,6,10,.72);color:#fff;cursor:pointer}.asset-actions :deep(.favorite-heart){position:static}.load-more{display:block;margin:28px auto 0;padding:8px 20px;border:1px solid var(--color-border);border-radius:7px;background:transparent;color:var(--color-muted);cursor:pointer}.state{padding:90px 0;color:var(--color-faint);text-align:center}@media(max-width:760px){.detail{padding:28px 18px 60px}.filters{align-items:stretch;flex-direction:column;gap:12px}.filters>div{width:100%;overflow-x:auto}.masonry{columns:1}.asset-actions{opacity:1}header small{display:none}}
</style>
