<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElInput } from 'element-plus'
import ProjectCard from '../components/ProjectCard.vue'
import type { ProjectSummary } from '../types/project'
const router=useRouter(),projects=ref<ProjectSummary[]>([]),search=ref(''),scope=ref<'all'|'personal'|'shared'>('all'),loading=ref(true)
const user=()=>{try{return JSON.parse(localStorage.getItem('user')||'null')}catch{return null}}
const visible=computed(()=>projects.value.filter(p=>(scope.value==='all'||p.scope===scope.value)&&p.name.toLowerCase().includes(search.value.trim().toLowerCase())))
function openProject(project:ProjectSummary){sessionStorage.setItem('active-project',JSON.stringify({project,assets:project.cover_assets||[]}));router.push(`/projects/${project.id}`)}
onMounted(async()=>{try{const response=await fetch(`/api/api-proxy/projects?user_id=${user()?.id||''}`);if(!response.ok)throw new Error();projects.value=(await response.json()).projects||[]}catch{projects.value=[]}finally{loading.value=false}})
</script>
<template><main class="projects-page"><header><button class="crumb" @click="router.push('/')">工作台</button><span>/</span><strong>项目</strong><small>{{projects.length}} 个</small></header><section class="tools"><ElInput v-model="search" placeholder="搜索项目" clearable/><nav><button :class="{active:scope==='all'}" @click="scope='all'">全部</button><button :class="{active:scope==='personal'}" @click="scope='personal'">我的</button><button :class="{active:scope==='shared'}" @click="scope='shared'">团队共享</button></nav></section><div v-if="loading" class="state">正在加载项目…</div><div v-else-if="!visible.length" class="state">没有符合条件的项目</div><section v-else class="grid"><ProjectCard v-for="project in visible" :key="project.id" :project="project" @open="openProject(project)"/></section></main></template>
<style scoped>.projects-page{min-height:calc(100vh - 22px);padding:36px 40px 80px;color:var(--color-text);background:linear-gradient(180deg,rgba(2,4,8,.66),rgba(2,4,8,.56) 48%,rgba(2,4,8,.72))}header{display:flex;align-items:center;gap:9px;height:28px;color:var(--color-faint);font-size:12px}header .crumb{border:0;background:none;color:var(--color-muted);cursor:pointer}header strong{color:var(--color-text);font-size:15px;font-weight:560}header small{margin-left:3px;color:var(--color-faint)}.tools{margin:24px 0 22px;display:flex;align-items:center;justify-content:space-between;gap:20px}.tools :deep(.el-input){width:280px}.tools :deep(.el-input__wrapper){border:0!important;border-bottom:1px solid var(--color-border)!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}.tools nav{display:flex;gap:22px}.tools nav button{padding:0 0 7px;border:0;border-bottom:1px solid transparent;background:none;color:var(--color-muted);cursor:pointer}.tools nav button.active{border-color:var(--color-primary);color:var(--color-text)}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.state{padding:80px 0;color:var(--color-faint);text-align:center}@media(max-width:980px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.projects-page{padding:28px 18px 60px}.tools{align-items:stretch;flex-direction:column}.tools :deep(.el-input){width:100%}.grid{grid-template-columns:1fr}}</style>
